Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_version = "20220314.0.0"
    config.vm.hostname = "kind"
    config.vm.synced_folder "./", "/vagrant", disabled: true
    config.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/KANS/main/kind/init_cfg.sh"
    config.vm.provider "virtualbox" do |vb1|
      vb1.memory = 8192
      vb1.cpus = 4
      vb1.name = "kind"
      vb1.linked_clone = true
    end
    config.vm.network "private_network", ip: "192.168.30.10"
    config.vm.network "forwarded_port", guest: 22, host: 50310, auto_correct: true, id: "ssh"
  end
