# Base Image
BOX_IMAGE = "ubuntu/jammy64"
BOX_VERSION = "20220423.0.0"

# max number of worker nodes : Ex) N = 3
N = 2

# Version : Ex) k8s_V = '1.22.7'
k8s_V = '1.23.6'
cni_N = '5g'
calico_V = '3.22.2'

Vagrant.configure("2") do |config|
#-----Manager Node
    config.vm.define "k8s-m" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/#{cni_N}-Lab"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
        v.name = "#{cni_N}-k8s-m"
        v.memory = 2560
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-m"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.10.10"
      subconfig.vm.network "forwarded_port", guest: 22, host: 50010, auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/KANS/main/5g/init_cfg.sh", args: [ N, k8s_V ]
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/KANS/main/5g/master.sh", args: [ cni_N, calico_V ]
    end

#-----Worker Node Subnet1
  (1..N).each do |i|
    config.vm.define "k8s-w#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/#{cni_N}-Lab"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
        v.name = "#{cni_N}-k8s-w#{i}"
        v.memory = 2560
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-w#{i}"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.10.10#{i}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "5001#{i}", auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/KANS/main/5g/init_cfg.sh", args: [ N, k8s_V ]
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/KANS/main/5g/worker.sh", args: [ calico_V ]
    end
  end

end
