apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-app
spec:
  clusterIP: None
  ports:
    - name: '9092'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka-app
spec:
  serviceName: kafka-svc
  replicas: 3
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:   
      labels:   
        app: kafka-app   
    spec: 
      topologySpreadConstraints: 
        - maxSkew: 1                        # maxSkew describes the allowed drift for the pod distribution across the specified topology.
          topologyKey: topology.kubernetes.io/zone   # topologyKey is the name of the node label. All the nodes with the same label are considered in the same topology.
          whenUnsatisfiable: DoNotSchedule  # whenUnsatisfiable indicates what happens to a Pod that doesn't satisfy the spread constraint.
          labelSelector:                    # labelSelector is used to find matching Pods
            matchLabels:
              app: kafka-app
      containers:
        - name: kafka-container
          image: doughgle/kafka-kraft
          ports:
            - containerPort: 9092 
            - containerPort: 9093 
          env:                    
            - name: REPLICAS      
              value: '3'
            - name: SERVICE       
              value: kafka-svc
            - name: NAMESPACE
              value: default
            - name: SHARE_DIR     
              value: /mnt/kafka
            - name: CLUSTER_ID    
              value: oh-sxaDRTcyAr6pFRbXyzA
            - name: DEFAULT_REPLICATION_FACTOR
              value: '3'
            - name: DEFAULT_MIN_INSYNC_REPLICAS
              value: '2'
          volumeMounts:
            - name: data
              mountPath: /mnt/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"